openapi: 3.0.0
info:
  title: Course Rating API
  description: API for managing course ratings
  version: 1.0.0
paths:
  /api/course_ratings:
    get:
      summary: Get all course ratings
      responses:
        '200':
          description: A list of course ratings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CourseRating'
    post:
      summary: Create a new course rating
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseRating'
      responses:
        '201':
          description: Course rating created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseRating'

  /api/course_ratings/{rating_id}:
    get:
      summary: Get specific course rating by ID
      parameters:
        - name: rating_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Course rating details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseRating'
        '404':
          description: Course rating not found
    put:
      summary: Update specific course rating by ID
      parameters:
        - name: rating_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseRating'
      responses:
        '200':
          description: Updated course rating
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseRating'
        '404':
          description: Course rating not found
    delete:
      summary: Delete specific course rating by ID
      parameters:
        - name: rating_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Course rating deleted
        '404':
          description: Course rating not found

components:
  schemas:
    CourseRating:
      type: object
      properties:
        id:
          type: integer
          example: 1
        rating:
          type: number
          format: float
          example: 4.5
        comment:
          type: string
          example: "Great course!"
        user_id:
          type: integer
          example: 1
        course_id:
          type: integer
          example: 1
      required:
        - rating
        - user_id
        - course_id
