openapi: 3.0.0
info:
  title: Option API
  description: API for managing quiz options
  version: 1.0.0
paths:
  /api/options:
    get:
      summary: Get all options
      responses:
        '200':
          description: A list of quiz options
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Option'
    post:
      summary: Create a new option
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Option'
      responses:
        '201':
          description: Option created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Option'

  /api/options/{option_id}:
    get:
      summary: Get specific option by ID
      parameters:
        - name: option_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Option details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Option'
        '404':
          description: Option not found
    put:
      summary: Update specific option by ID
      parameters:
        - name: option_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Option'
      responses:
        '200':
          description: Updated option
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Option'
        '404':
          description: Option not found
    delete:
      summary: Delete specific option by ID
      parameters:
        - name: option_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Option deleted
        '404':
          description: Option not found

components:
  schemas:
    Option:
      type: object
      properties:
        id:
          type: integer
          example: 1
        content:
          type: string
          example: "Option content"
        is_correct:
          type: boolean
          example: true
        question_id:
          type: integer
          example: 1
      required:
        - content
        - is_correct
        - question_id
