openapi: 3.0.0
info:
  title: Question API
  description: API for managing quiz questions
  version: 1.0.0
paths:
  /api/questions:
    get:
      summary: Get all questions
      responses:
        '200':
          description: A list of quiz questions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
    post:
      summary: Create a new question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
      responses:
        '201':
          description: Question created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'

  /api/questions/{question_id}:
    get:
      summary: Get specific question by ID
      parameters:
        - name: question_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Question details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
        '404':
          description: Question not found
    put:
      summary: Update specific question by ID
      parameters:
        - name: question_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
      responses:
        '200':
          description: Updated question
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
        '404':
          description: Question not found
    delete:
      summary: Delete specific question by ID
      parameters:
        - name: question_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Question deleted
        '404':
          description: Question not found

components:
  schemas:
    Question:
      type: object
      properties:
        id:
          type: integer
          example: 1
        content:
          type: string
          example: "What is the capital of France?"
        quiz_id:
          type: integer
          example: 1
      required:
        - content
        - quiz_id
