openapi: 3.0.0
info:
  title: Quiz API
  description: API for managing quizzes
  version: 1.0.0
paths:
  /api/quizzes:
    get:
      summary: Get all quizzes
      responses:
        '200':
          description: A list of quizzes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quiz'
    post:
      summary: Create a new quiz
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quiz'
      responses:
        '201':
          description: Quiz created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'

  /api/quizzes/{quiz_id}:
    get:
      summary: Get a specific quiz by ID
      parameters:
        - name: quiz_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Quiz details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
        '404':
          description: Quiz not found
    put:
      summary: Update a specific quiz by ID
      parameters:
        - name: quiz_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quiz'
      responses:
        '200':
          description: Updated quiz
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
        '404':
          description: Quiz not found
    delete:
      summary: Delete a specific quiz by ID
      parameters:
        - name: quiz_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Quiz deleted
        '404':
          description: Quiz not found

components:
  schemas:
    Quiz:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Sample Quiz Title"
        created_at:
          type: string
          format: date-time
          example: "2024-07-31T12:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2024-07-31T12:00:00Z"
        questions:
          type: array
          items:
            $ref: '#/components/schemas/Question'
        results:
          type: array
          items:
            $ref: '#/components/schemas/QuizResult'
      required:
        - title

    Question:
      type: object
      properties:
        id:
          type: integer
          example: 1
        content:
          type: string
          example: "What is the capital of France?"
        quiz_id:
          type: integer
          example: 1
        created_at:
          type: string
          format: date-time
          example: "2024-07-31T12:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2024-07-31T12:00:00Z"
        quiz:
          $ref: '#/components/schemas/Quiz'
        options:
          type: array
          items:
            $ref: '#/components/schemas/Option'

    Option:
      type: object
      properties:
        id:
          type: integer
          example: 1
        content:
          type: string
          example: "Paris"
        is_correct:
          type: boolean
          example: true
        question_id:
          type: integer
          example: 1
        created_at:
          type: string
          format: date-time
          example: "2024-07-31T12:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2024-07-31T12:00:00Z"
        question:
          $ref: '#/components/schemas/Question'

    QuizResult:
      type: object
      properties:
        id:
          type: integer
          example: 1
        score:
          type: number
          format: float
          example: 85.5
        user_id:
          type: integer
          example: 1
        quiz_id:
          type: integer
          example: 1
        created_at:
          type: string
          format: date-time
          example: "2024-07-31T12:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2024-07-31T12:00:00Z"
        quiz:
          $ref: '#/components/schemas/Quiz'
        user:
          $ref: '#/components/schemas/User'
