openapi: 3.0.0
info:
  title: Quiz Result API
  description: API for managing quiz results
  version: 1.0.0
paths:
  /api/quiz_results:
    get:
      summary: Get all quiz results
      responses:
        '200':
          description: A list of quiz results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QuizResult'
    post:
      summary: Create a new quiz result
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuizResult'
      responses:
        '201':
          description: Quiz result created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizResult'

  /api/quiz_results/{result_id}:
    get:
      summary: Get a specific quiz result by ID
      parameters:
        - name: result_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Quiz result details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizResult'
        '404':
          description: Quiz result not found
    put:
      summary: Update a specific quiz result by ID
      parameters:
        - name: result_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuizResult'
      responses:
        '200':
          description: Updated quiz result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizResult'
        '404':
          description: Quiz result not found
    delete:
      summary: Delete a specific quiz result by ID
      parameters:
        - name: result_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Quiz result deleted
        '404':
          description: Quiz result not found

components:
  schemas:
    QuizResult:
      type: object
      properties:
        id:
          type: integer
          example: 1
        score:
          type: number
          format: float
          example: 95.5
        user_id:
          type: integer
          example: 1
        quiz_id:
          type: integer
          example: 1
      required:
        - score
        - user_id
        - quiz_id
