openapi: 3.0.0
info:
  title: Resource API
  description: API for managing resources
  version: 1.0.0
paths:
  /api/resources:
    get:
      summary: Get a list of all resources
      responses:
        '200':
          description: List of resources
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Resource'
    post:
      summary: Create a new resource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource'
      responses:
        '201':
          description: Resource created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
  /api/resources/{resource_id}:
    get:
      summary: Get a specific resource by ID
      parameters:
        - name: resource_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Resource details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
        '404':
          description: Resource not found
    put:
      summary: Update a specific resource by ID
      parameters:
        - name: resource_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource'
      responses:
        '200':
          description: Resource updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
        '404':
          description: Resource not found
    delete:
      summary: Delete a specific resource by ID
      parameters:
        - name: resource_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Resource deleted
        '404':
          description: Resource not found

components:
  schemas:
    Resource:
      type: object
      properties:
        id:
          type: integer
        url:
          type: string
        course_id:
          type: integer
        course:
          type: object
          properties:
            id:
              type: integer
            title:
              type: string
            description:
              type: string
