openapi: 3.0.0
info:
  title: Video API
  description: API for managing videos
  version: 1.0.0
paths:
  /api/videos:
    get:
      summary: Get all videos
      responses:
        '200':
          description: A list of videos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Video'
    post:
      summary: Create a new video
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Video'
      responses:
        '201':
          description: Video created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'

  /api/videos/{video_id}:
    get:
      summary: Get a specific video by ID
      parameters:
        - name: video_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Video details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
        '404':
          description: Video not found
    put:
      summary: Update a specific video by ID
      parameters:
        - name: video_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Video'
      responses:
        '200':
          description: Updated video
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
        '404':
          description: Video not found
    delete:
      summary: Delete a specific video by ID
      parameters:
        - name: video_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Video deleted
        '404':
          description: Video not found

components:
  schemas:
    Video:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "New Video"
        url:
          type: string
          example: "http://example.com/video"
        course_id:
          type: integer
          example: 1
      required:
        - title
        - url
        - course_id
